import { NextResponse } from "next/server";
import { requirePrivileged } from "@/lib/auth/authorization";
import { addEvidence, score, transition, type M14State } from "@/lib/productization";
import { getRequestId } from "@/lib/security/request-id";

export const runtime="nodejs";
export const dynamic="force-dynamic";
const problem=(status:number,code:string,title:string,requestId:string,detail?:string)=>NextResponse.json({type:`https://tinlance.com/problems/${code}`,title,status,detail:detail??title,code,requestId},{status,headers:{"content-type":"application/problem+json","cache-control":"no-store","x-request-id":requestId}});
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const requestId=getRequestId(request);const auth=await requirePrivileged();if(!auth)return problem(401,"unauthorized","Authentication required",requestId);if(!auth.organizationId||!auth.userId)return problem(403,"organization_required","An active organization is required",requestId);const {id}=await params;try{const b=await request.json();const action=String(b.action??"");if(action==="evidence"){const result=await addEvidence({userId:auth.userId,organizationId:auth.organizationId,requestId,opportunityId:id,evidenceType:String(b.evidenceType??""),sourceType:String(b.sourceType??""),sourceId:String(b.sourceId??""),summary:String(b.summary??""),classification:String(b.classification??"INTERNAL"),purpose:String(b.purpose??""),retentionUntil:b.retentionUntil,m13CandidateId:b.m13CandidateId});return NextResponse.json(result,{status:201,headers:{"cache-control":"no-store","x-request-id":requestId}});}if(action==="score"){const result=await score({userId:auth.userId,organizationId:auth.organizationId,requestId,opportunityId:id,dimensions:b.dimensions});return NextResponse.json(result,{headers:{"cache-control":"no-store","x-request-id":requestId}});}if(action==="transition"){const result=await transition({userId:auth.userId,organizationId:auth.organizationId,requestId,opportunityId:id,to:b.to as M14State,rationale:String(b.rationale??""),approvalPresent:b.approvalPresent===true});return NextResponse.json(result,{headers:{"cache-control":"no-store","x-request-id":requestId}});}return problem(400,"invalid_action","Unsupported M14 opportunity action",requestId);}catch(error){const code=error instanceof Error?error.message:"m14_action_failed";const status=code.includes("security")||code.includes("ai_cannot")?403:code.includes("not_found")?404:code.includes("evaluation_required")||code.includes("security_review_required")||code.includes("insufficient")?422:400;return problem(status,code,"M14 opportunity action failed",requestId);}}
