import { notFound, redirect } from "next/navigation";
import { headers } from "next/headers";
import { PortalShell } from "../../../../../components/portal-shell";
import { ProjectNav } from "../../../../../components/workspace/project-nav";
import { auth } from "../../../../../lib/auth";
import { authorizeProject } from "../../../../../lib/workspace/authorization";
import { db } from "../../../../../lib/db";

export default async function FindingsPage({ params }: { params: Promise<{ projectId: string }> }) { const session = await auth.api.getSession({ headers: await headers() }); if (!session) redirect("/sign-in"); const { projectId } = await params; const authorized = await authorizeProject(projectId, "finding:read"); if (!authorized) notFound(); const findings = await db.workspaceFinding.findMany({ where: { projectId, organizationId: authorized.project.organizationId, ...(authorized.principal.isPrivileged ? {} : { visibility: { in: ["CUSTOMER","CUSTOMER_CONFIDENTIAL"] } }) }, orderBy: [{ severity: "asc" }, { createdAt: "desc" }], take: 100 }); return <PortalShell active="projects"><div className="portal-page-head"><div><p className="kicker">FINDINGS / TRACEABILITY</p><h1>What was found.</h1><p>Every customer-visible conclusion is tied to an assessment and evidence.</p></div></div><ProjectNav projectId={projectId} active="findings" /><div className="portal-project-list portal-project-list-large">{findings.length ? findings.map((f) => <article className="portal-project-detail" key={f.id}><div className="portal-project-copy"><span className="portal-project-status"><span aria-hidden="true" />{f.severity} · {f.status}</span><h2>{f.title}</h2><p>{f.description}</p><p><strong>Recommendation:</strong> {f.recommendation}</p></div><div className="portal-detail-metrics"><span>Category<strong>{f.category}</strong></span><span>Asset<strong>{f.affectedAsset ?? "—"}</strong></span><span>Due<strong>{f.dueDate?.toLocaleDateString() ?? "—"}</strong></span></div></article>) : <section className="portal-panel"><p className="kicker">NO CUSTOMER-VISIBLE FINDINGS</p><h2>No reviewed findings yet.</h2><p>Internal analysis remains protected until it is explicitly disclosed.</p></section>}</div></PortalShell>; }
