import { redirect } from "next/navigation";
import Link from "next/link";
import { AdminShell } from "../../../components/admin-shell";
import { requirePrivileged } from "../../../lib/auth/authorization";
import { listOpportunities } from "../../../lib/productization";

export const dynamic="force-dynamic";
export const revalidate=0;
export default async function ProductizationPage(){const auth=await requirePrivileged();if(!auth)redirect("/sign-in");if(!auth.organizationId||!auth.userId)redirect("/admin");const items=await listOpportunities({userId:auth.userId,organizationId:auth.organizationId,requestId:`admin-productization-${Date.now()}`});return <AdminShell active="productization"><div className="admin-page-head"><div><p className="kicker">TINLANCE / M14</p><h1>Consulting → software flywheel</h1><p>Evidence-backed productization portfolio. This view never treats a score as product-market fit.</p></div><Link href="/admin" className="text-link">Control center</Link></div><section className="admin-section"><div className="admin-section-head"><div><p className="kicker">PORTFOLIO</p><h2>Productization opportunities</h2></div></div><div className="admin-action-list">{items.length===0?<article><div><strong>No opportunities yet.</strong><p>Create observations from authorized delivery evidence, validate recurrence, then promote the pattern.</p></div></article>:items.map((item)=><article key={String(item.id)}><div><strong>{String(item.title)}</strong><p>{String(item.targetSegment)} · {String(item.decisionTrack)} · {String(item.lifecycleState)}</p></div><div style={{textAlign:"right"}}><strong>{item.scoreTotal===null?"—":String(item.scoreTotal)}</strong><p>score · evidence {String(item.evidenceQuality)}</p></div></article>)}</div></section><section className="admin-two-col"><section className="admin-panel"><p className="kicker">GUARDRAILS</p><h2>Promotion requires evidence</h2><p>Cross-customer intelligence must arrive through M13 governance. AI recommendations cannot approve lifecycle transitions. Product validation requires an M8 PASS and productization requires a security PASS.</p></section><section className="admin-panel admin-panel-dark"><p className="kicker kicker-dark">COMMERCIAL TRUTH</p><h2>M12 remains authoritative</h2><p>M14 records productization decisions and delivery economics; canonical revenue, funnel and recurring-revenue metrics remain in M12.</p></section></section></AdminShell>}
