import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { headers } from "next/headers";
import { PortalShell } from "../../../../../components/portal-shell";
import { ProjectNav } from "../../../../../components/workspace/project-nav";
import { auth } from "../../../../../lib/auth";
import { authorizeProject } from "../../../../../lib/workspace/authorization";
import { db } from "../../../../../lib/db";

export default async function ReportsPage({ params }: { params: Promise<{ projectId: string }> }) { const session = await auth.api.getSession({ headers: await headers() }); if (!session) redirect("/sign-in"); const { projectId } = await params; const authorized = await authorizeProject(projectId, "report:read"); if (!authorized) notFound(); const reports = await db.workspaceReport.findMany({ where: { projectId, organizationId: authorized.project.organizationId, ...(authorized.principal.isPrivileged ? {} : { status: { in: ["APPROVED","PUBLISHED","SUPERSEDED"] } }) }, orderBy: { createdAt: "desc" }, take: 50 }); return <PortalShell active="projects"><div className="portal-page-head"><div><p className="kicker">REPORTS / DELIVERABLES</p><h1>Assessment reports.</h1><p>Published reports are versioned deliverables. Corrections create new versions rather than overwriting history.</p></div></div><ProjectNav projectId={projectId} active="reports" /><div className="portal-project-list portal-project-list-large">{reports.length ? reports.map((r) => <article className="portal-project-detail" key={r.id}><div className="portal-project-copy"><span className="portal-project-status"><span aria-hidden="true" />{r.status}</span><h2>{r.title}</h2><p>{r.summary}</p></div><div className="portal-detail-metrics"><span>Version<strong>v{r.currentVersion}</strong></span><span>Published<strong>{r.publishedAt?.toLocaleDateString() ?? "—"}</strong></span><span><Link className="text-link" href={`/api/v1/workspace/reports/${r.id}`}>View report</Link></span></div></article>) : <section className="portal-panel"><p className="kicker">NO PUBLISHED REPORTS</p><h2>No customer report has been issued yet.</h2></section>}</div></PortalShell>; }
