import { NextResponse } from "next/server";
import { requirePrivileged } from "@/lib/auth/authorization";
import { createObservation } from "@/lib/productization";
import { db } from "@/lib/db";
import { Prisma } from "@prisma/client";
import { getRequestId } from "@/lib/security/request-id";

export const runtime="nodejs";
export const dynamic="force-dynamic";
const problem=(status:number,code:string,title:string,requestId:string,detail?:string)=>NextResponse.json({type:`https://tinlance.com/problems/${code}`,title,status,detail:detail??title,code,requestId},{status,headers:{"content-type":"application/problem+json","cache-control":"no-store","x-request-id":requestId}});
export async function POST(request:Request){const requestId=getRequestId(request);const auth=await requirePrivileged();if(!auth)return problem(401,"unauthorized","Authentication required",requestId);if(!auth.organizationId||!auth.userId)return problem(403,"organization_required","An active organization is required",requestId);try{const body=await request.json();const result=await createObservation({userId:auth.userId,organizationId:auth.organizationId,requestId,sourceType:String(body.sourceType??""),sourceId:String(body.sourceId??""),category:String(body.category??""),problemStatement:String(body.problemStatement??""),observedOutcome:body.observedOutcome, severity:body.severity,frequencySignal:body.frequencySignal,customerImpact:body.customerImpact,businessImpact:body.businessImpact,technicalImpact:body.technicalImpact,classification:String(body.classification??"INTERNAL"),provenance:body.provenance??{}});return NextResponse.json(result,{status:201,headers:{"cache-control":"no-store","x-request-id":requestId}});}catch(error){const code=error instanceof Error?error.message:"m14_observation_failed";return problem(code.startsWith("m14_invalid")?400:code.includes("security")?403:500,code,"M14 observation could not be created",requestId);}}
export async function GET(request:Request){const requestId=getRequestId(request);const auth=await requirePrivileged();if(!auth)return problem(401,"unauthorized","Authentication required",requestId);if(!auth.organizationId)return problem(403,"organization_required","An active organization is required",requestId);const url=new URL(request.url);const limit=Math.min(Math.max(Number(url.searchParams.get("limit")??50),1),100);const rows=await db.$queryRaw<Array<Record<string,unknown>>>(Prisma.sql`SELECT id,"sourceType","sourceId","problemCategory","problemStatement",severity,status,"createdAt" FROM "ProductizationObservation" WHERE "organizationId"=${auth.organizationId} ORDER BY "createdAt" DESC LIMIT ${limit}`);return NextResponse.json({items:rows},{headers:{"cache-control":"no-store","x-request-id":requestId}});}
