import { z } from "zod";
import { authenticateApi, ok, problem } from "@/lib/api/v1";
import { getRequestId } from "@/lib/security/request-id";
import { authorizeAgentManagement } from "@/lib/agent-runtime/authorization";
import { loadMemory, writeMemory } from "@/lib/agent-runtime/store";

const schema = z.object({ scope: z.enum(["WORKING", "EXECUTION", "AGENT", "ORGANIZATION", "PROJECT", "CUSTOMER"]), subjectId: z.string().trim().max(200).optional(), classification: z.enum(["PUBLIC", "INTERNAL", "CONFIDENTIAL", "SENSITIVE", "RESTRICTED"]), trust: z.enum(["UNTRUSTED", "EXTERNAL", "USER", "VERIFIED"]).default("UNTRUSTED"), content: z.string().min(1).max(65536), source: z.string().trim().min(1).max(200), provenance: z.record(z.string(), z.unknown()).default({}), expiresAt: z.string().datetime().optional() });

export async function GET(request: Request, context: { params: Promise<{ agentId: string }> }) { const auth = await authenticateApi(request); if ("response" in auth) return auth.response; const requestId = getRequestId(request); const { agentId } = await context.params; const decision = await authorizeAgentManagement({ organizationId: auth.principal.organizationId, userId: auth.principal.userId, action: "agent.memory.read", resourceId: agentId, requestId }); if (decision.decision !== "ALLOW") return problem(requestId, 403, "memory_authorization_denied", "Memory access denied"); return ok(request, { memory: await loadMemory({ organizationId: auth.principal.organizationId, agentId }) }); }

export async function POST(request: Request, context: { params: Promise<{ agentId: string }> }) { const auth = await authenticateApi(request); if ("response" in auth) return auth.response; const requestId = getRequestId(request); const { agentId } = await context.params; const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return problem(requestId, 400, "invalid_memory_request", "Invalid memory request", parsed.error.message); const decision = await authorizeAgentManagement({ organizationId: auth.principal.organizationId, userId: auth.principal.userId, action: "agent.memory.write", resourceId: agentId, requestId }); if (decision.decision !== "ALLOW") return problem(requestId, 403, "memory_authorization_denied", "Memory write denied"); try { const id = await writeMemory({ organizationId: auth.principal.organizationId, userId: auth.principal.userId, agentId, ...parsed.data, expiresAt: parsed.data.expiresAt ? new Date(parsed.data.expiresAt) : undefined }); return ok(request, { memoryId: id }, 201); } catch (error) { return problem(requestId, 422, "memory_write_failed", "Memory could not be written", error instanceof Error ? error.message : "Unknown memory error"); } }
