CREATE OR REPLACE FUNCTION classification_rank(value TEXT) RETURNS INTEGER LANGUAGE SQL IMMUTABLE AS $$
  SELECT CASE value WHEN 'PUBLIC' THEN 0 WHEN 'INTERNAL' THEN 1 WHEN 'CONFIDENTIAL' THEN 2 WHEN 'RESTRICTED' THEN 3 WHEN 'SECRET' THEN 4 ELSE 99 END;
$$;
