import { createHash } from "node:crypto";

type ReportFinding = { id: string; title: string; description: string; severity: string; category: string; affectedAsset: string | null; recommendation: string; };
type ReportEvidence = { id: string; title: string; contentHash: string; type: string; };
type ReportRemediation = { findingId: string; title: string; status: string; priority: string; };

function escapeHtml(value: string) {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
}

export function generateAssessmentReport(input: { title: string; projectName: string; assessmentType: string; assessmentPeriod: string; objective: string; methodology: string; findings: ReportFinding[]; evidence: ReportEvidence[]; remediation: ReportRemediation[]; limitations?: string }) {
  const severityOrder = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"];
  const counts = severityOrder.map((severity) => `${severity}: ${input.findings.filter((f) => f.severity === severity).length}`).join(" · ");
  const content = `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${escapeHtml(input.title)}</title><style>body{font-family:system-ui,sans-serif;max-width:960px;margin:40px auto;padding:0 24px;line-height:1.6;color:#111}h1,h2{line-height:1.2}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ddd;padding:8px;text-align:left;vertical-align:top}.finding{break-inside:avoid;border:1px solid #ddd;padding:16px;margin:16px 0}code{word-break:break-all}.meta{color:#555}</style></head><body><header><p class="meta">TINLANCE SECURITY / TECHNICAL ASSESSMENT</p><h1>${escapeHtml(input.title)}</h1><p class="meta">Project: ${escapeHtml(input.projectName)} · Assessment: ${escapeHtml(input.assessmentType)} · Period: ${escapeHtml(input.assessmentPeriod)}</p></header><h2>Executive Summary</h2><p>${escapeHtml(input.findings.length ? `The assessment identified ${input.findings.length} findings. ${counts}.` : "No findings were recorded in the report dataset.")}</p><h2>Scope &amp; Objectives</h2><p>${escapeHtml(input.objective)}</p><h2>Methodology</h2><p>${escapeHtml(input.methodology)}</p><h2>Findings</h2>${input.findings.map((f) => `<section class="finding"><h3>${escapeHtml(f.title)}</h3><p><strong>Severity:</strong> ${escapeHtml(f.severity)} · <strong>Category:</strong> ${escapeHtml(f.category)}</p><p>${escapeHtml(f.description)}</p><p><strong>Affected asset:</strong> ${escapeHtml(f.affectedAsset ?? "Not specified")}</p><p><strong>Recommendation:</strong> ${escapeHtml(f.recommendation)}</p></section>`).join("")}<h2>Evidence Traceability</h2><table><thead><tr><th>Evidence</th><th>Type</th><th>SHA-256</th></tr></thead><tbody>${input.evidence.map((e) => `<tr><td>${escapeHtml(e.title)} <code>${escapeHtml(e.id)}</code></td><td>${escapeHtml(e.type)}</td><td><code>${escapeHtml(e.contentHash)}</code></td></tr>`).join("")}</tbody></table><h2>Remediation Priorities</h2><table><thead><tr><th>Finding</th><th>Action</th><th>Priority</th><th>Status</th></tr></thead><tbody>${input.remediation.map((r) => `<tr><td><code>${escapeHtml(r.findingId)}</code></td><td>${escapeHtml(r.title)}</td><td>${escapeHtml(r.priority)}</td><td>${escapeHtml(r.status)}</td></tr>`).join("")}</tbody></table><h2>Limitations &amp; Assumptions</h2><p>${escapeHtml(input.limitations ?? "This report reflects the scope, evidence and methodology recorded in the Tinlance workspace at publication time. It is not a certification or compliance attestation.")}</p></body></html>`;
  return { content, contentHash: createHash("sha256").update(content).digest("hex") };
}
