import { notFound, redirect } from "next/navigation";
import { headers } from "next/headers";
import { PortalShell } from "../../../../../components/portal-shell";
import { ProjectNav } from "../../../../../components/workspace/project-nav";
import { auth } from "../../../../../lib/auth";
import { authorizeProject } from "../../../../../lib/workspace/authorization";
import { db } from "../../../../../lib/db";

export default async function EvidencePage({ params }: { params: Promise<{ projectId: string }> }) { const session = await auth.api.getSession({ headers: await headers() }); if (!session) redirect("/sign-in"); const { projectId } = await params; const authorized = await authorizeProject(projectId, "evidence:read"); if (!authorized) notFound(); const [evidence, requests] = await Promise.all([db.workspaceEvidence.findMany({ where: { projectId, organizationId: authorized.project.organizationId, visibility: { in: ["CUSTOMER","CUSTOMER_CONFIDENTIAL"] } }, orderBy: { createdAt: "desc" }, take: 100, select: { id: true, title: true, type: true, mimeType: true, sizeBytes: true, contentHash: true, integrityStatus: true, collectedAt: true } }), db.workspaceEvidenceRequest.findMany({ where: { projectId, organizationId: authorized.project.organizationId, status: { in: ["REQUESTED","REOPENED","REVIEWING"] } }, orderBy: { dueDate: "asc" }, take: 50 })]); return <PortalShell active="projects"><div className="portal-page-head"><div><p className="kicker">EVIDENCE / INTEGRITY</p><h1>Evidence trail.</h1><p>Private evidence is classified, hashed and accessed through an authorization boundary.</p></div></div><ProjectNav projectId={projectId} active="evidence" /><section className="portal-section"><div className="portal-section-head"><div><p className="kicker">REQUESTS</p><h2>Evidence requested</h2></div></div><div className="portal-project-list">{requests.map((r) => <article className="portal-project-detail" key={r.id}><div className="portal-project-copy"><span className="portal-project-status"><span aria-hidden="true" />{r.status}</span><h2>{r.title}</h2><p>{r.description}</p></div><div className="portal-detail-metrics"><span>Type<strong>{r.requestedType}</strong></span><span>Due<strong>{r.dueDate?.toLocaleDateString() ?? "—"}</strong></span></div></article>)}</div></section><section className="portal-section"><div className="portal-section-head"><div><p className="kicker">COLLECTED</p><h2>Verified evidence</h2></div></div><div className="portal-project-list">{evidence.length ? evidence.map((e) => <article className="portal-project-detail" key={e.id}><div className="portal-project-copy"><span className="portal-project-status"><span aria-hidden="true" />{e.integrityStatus}</span><h2>{e.title}</h2><p>{e.type} · {e.mimeType} · {e.sizeBytes.toString()} bytes</p><p><code>{e.contentHash}</code></p></div><div className="portal-detail-metrics"><span>Collected<strong>{e.collectedAt.toLocaleDateString()}</strong></span></div></article>) : <section className="portal-panel"><p className="kicker">NO EVIDENCE</p><h2>No evidence has been collected yet.</h2></section>}</div></section></PortalShell>; }
