import { notFound, redirect } from "next/navigation";
import { headers } from "next/headers";
import { PortalShell } from "../../../../../components/portal-shell";
import { ProjectNav } from "../../../../../components/workspace/project-nav";
import { auth } from "../../../../../lib/auth";
import { authorizeProject } from "../../../../../lib/workspace/authorization";
import { db } from "../../../../../lib/db";

export default async function AssessmentsPage({ params }: { params: Promise<{ projectId: string }> }) { const session = await auth.api.getSession({ headers: await headers() }); if (!session) redirect("/sign-in"); const { projectId } = await params; const authorized = await authorizeProject(projectId, "assessment:read"); if (!authorized) notFound(); const items = await db.workspaceAssessment.findMany({ where: { projectId, organizationId: authorized.project.organizationId }, orderBy: { createdAt: "desc" }, take: 50 }); return <PortalShell active="projects"><div className="portal-page-head"><div><p className="kicker">ASSESSMENTS</p><h1>Assessment lifecycle.</h1><p>Scope, execution state, methodology and results remain attached to this project.</p></div></div><ProjectNav projectId={projectId} active="assessments" /><div className="portal-project-list portal-project-list-large">{items.length ? items.map((item) => <article className="portal-project-detail" key={item.id}><div className="portal-project-copy"><span className="portal-project-status"><span aria-hidden="true" />{item.status}</span><h2>{item.type}</h2><p>{item.objective}</p></div><div className="portal-detail-metrics"><span>Result<strong>{item.resultStatus}</strong></span><span>Version<strong>{item.version}</strong></span><span>Completed<strong>{item.completedAt?.toLocaleDateString() ?? "—"}</strong></span></div></article>) : <section className="portal-panel"><p className="kicker">NO TECHNICAL ASSESSMENTS</p><h2>No scoped assessment is attached yet.</h2><p>Tinlance will attach the technical execution record to an existing commercial assessment.</p></section>}</div></PortalShell>; }
