import { NextResponse } from "next/server";
import { requirePrivileged } from "@/lib/auth/authorization";
import { createOpportunity, listOpportunities } from "@/lib/productization";
import { getRequestId } from "@/lib/security/request-id";
import type { M14State } from "@/lib/productization";

export const runtime="nodejs";
export const dynamic="force-dynamic";
const problem=(status:number,code:string,title:string,requestId:string,detail?:string)=>NextResponse.json({type:`https://tinlance.com/problems/${code}`,title,status,detail:detail??title,code,requestId},{status,headers:{"content-type":"application/problem+json","cache-control":"no-store","x-request-id":requestId}});
export async function GET(request:Request){const requestId=getRequestId(request);const auth=await requirePrivileged();if(!auth)return problem(401,"unauthorized","Authentication required",requestId);if(!auth.organizationId||!auth.userId)return problem(403,"organization_required","An active organization is required",requestId);try{const state=new URL(request.url).searchParams.get("state") as M14State|undefined;return NextResponse.json({items:await listOpportunities({userId:auth.userId,organizationId:auth.organizationId,requestId,state})},{headers:{"cache-control":"no-store","x-request-id":requestId}});}catch(error){return problem(500,"m14_list_failed","M14 opportunities could not be listed",requestId,error instanceof Error?error.message:undefined);}}
export async function POST(request:Request){const requestId=getRequestId(request);const auth=await requirePrivileged();if(!auth)return problem(401,"unauthorized","Authentication required",requestId);if(!auth.organizationId||!auth.userId)return problem(403,"organization_required","An active organization is required",requestId);try{const body=await request.json();const result=await createOpportunity({userId:auth.userId,organizationId:auth.organizationId,requestId,patternId:String(body.patternId??""),title:String(body.title??""),targetSegment:String(body.targetSegment??""),buyer:body.buyer,measurableOutcome:String(body.measurableOutcome??""),decisionTrack:body.decisionTrack});return NextResponse.json(result,{status:201,headers:{"cache-control":"no-store","x-request-id":requestId}});}catch(error){const code=error instanceof Error?error.message:"m14_opportunity_failed";return problem(code.includes("security")?403:code.includes("not_found")?404:400,code,"M14 opportunity could not be created",requestId);}}
