import { notFound, redirect } from "next/navigation";
import { headers } from "next/headers";
import { PortalShell } from "../../../../../components/portal-shell";
import { ProjectNav } from "../../../../../components/workspace/project-nav";
import { auth } from "../../../../../lib/auth";
import { authorizeProject } from "../../../../../lib/workspace/authorization";
import { db } from "../../../../../lib/db";

export default async function RemediationPage({ params }: { params: Promise<{ projectId: string }> }) { const session = await auth.api.getSession({ headers: await headers() }); if (!session) redirect("/sign-in"); const { projectId } = await params; const authorized = await authorizeProject(projectId, "remediation:read"); if (!authorized) notFound(); const items = await db.workspaceRemediation.findMany({ where: { projectId, organizationId: authorized.project.organizationId }, orderBy: { updatedAt: "desc" }, take: 100 }); return <PortalShell active="projects"><div className="portal-page-head"><div><p className="kicker">REMEDIATION / VERIFICATION</p><h1>Fixes with proof.</h1><p>A customer attestation can request verification; it cannot masquerade as independent verification.</p></div></div><ProjectNav projectId={projectId} active="remediation" /><div className="portal-project-list portal-project-list-large">{items.length ? items.map((item) => <article className="portal-project-detail" key={item.id}><div className="portal-project-copy"><span className="portal-project-status"><span aria-hidden="true" />{item.status}</span><h2>{item.title}</h2><p>{item.description}</p></div><div className="portal-detail-metrics"><span>Priority<strong>{item.priority}</strong></span><span>Target<strong>{item.targetDate?.toLocaleDateString() ?? "—"}</strong></span><span>Verification<strong>{item.verificationStatus}</strong></span></div></article>) : <section className="portal-panel"><p className="kicker">NO REMEDIATION</p><h2>No remediation work items yet.</h2></section>}</div></PortalShell>; }
