import { z } from "zod";
import { randomUUID } from "node:crypto";
import { Prisma } from "@prisma/client";
import { db } from "@/lib/db";
import { authenticateApi, ok, problem } from "@/lib/api/v1";
import { getRequestId } from "@/lib/security/request-id";
import { buildPrincipal, enforceSecurity } from "@/lib/security-gateway";
import { hasWorkspacePermission } from "@/lib/workspace/permissions";
const schema=z.object({agentId:z.string().min(1).max(200),collectionId:z.string().min(1).max(200),maxClassification:z.enum(["PUBLIC","INTERNAL","CONFIDENTIAL","RESTRICTED"]),scope:z.record(z.string(),z.unknown()).default({}),expiresAt:z.string().datetime().optional()});
export async function POST(request:Request){const auth=await authenticateApi(request);if("response" in auth)return auth.response;const requestId=getRequestId(request);const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return problem(requestId,400,"invalid_knowledge_agent_grant","Invalid knowledge agent grant",parsed.error.message);const member=await db.$queryRaw<Array<{role:string;globalRole:string}>>(Prisma.sql`SELECT m.role,u.role AS "globalRole" FROM "Member" m JOIN "User" u ON u.id=m."userId" WHERE m."organizationId"=${auth.principal.organizationId} AND m."userId"=${auth.principal.userId} LIMIT 1`);if(!member[0]||!hasWorkspacePermission({memberRole:member[0].role,isPrivileged:["admin","super-admin"].includes(member[0].globalRole)},"knowledge:share"))return problem(requestId,403,"knowledge_agent_grant_denied","Knowledge agent grant denied");const m7=await enforceSecurity({principal:buildPrincipal({principalId:auth.principal.userId,principalType:"HUMAN",organizationId:auth.principal.organizationId,userId:auth.principal.userId}),action:"knowledge.share",resourceType:"KnowledgeAgentGrant",requestedRisk:"HIGH",context:{tenantId:auth.principal.organizationId,requiredPermission:"knowledge:share"},requestId});if(m7.decision!=="ALLOW")return problem(requestId,403,"knowledge_agent_grant_denied","Knowledge agent grant denied");const id=`kag_${randomUUID().replaceAll("-","")}`;await db.$executeRaw(Prisma.sql`INSERT INTO "KnowledgeAgentGrant" ("id","organizationId","agentId","collectionId","maxClassification","scope","expiresAt","createdByUserId") VALUES (${id},${auth.principal.organizationId},${parsed.data.agentId},${parsed.data.collectionId},${parsed.data.maxClassification},${JSON.stringify(parsed.data.scope)}::jsonb,${parsed.data.expiresAt?new Date(parsed.data.expiresAt):null},${auth.principal.userId}) ON CONFLICT ("organizationId","agentId","collectionId") DO UPDATE SET "maxClassification"=EXCLUDED."maxClassification","scope"=EXCLUDED."scope","expiresAt"=EXCLUDED."expiresAt","revokedAt"=NULL`);return ok(request,{id},201)}
